name: build_context
description: A package that simplifies the access most of used properties/fuctions right in the BuildContext.
version: 1.1.0
homepage: https://github.com/pedromassango/build_context

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter